name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Building Swiss on FHIR
        run: |
          docker buildx build \
          --tag omarhoblos/swiss-on-fhir:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push to Docker Hub
        run: |
          docker buildx build --push \
            --tag omarhoblos/swiss-on-fhir:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
